# Generated by Django 3.1.6 on 2021-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
